version: 0.0
os: linux
files:
  # 배포파일에 대한 설정
  - source: /
    # 인스턴스에 복사할 디렉토리 경로
    destination: /home/ubuntu/app/
    # 인스턴스에 파일이 복사될 위치
    overwrite: yes
    # 복사할 위치에 파일이 있는 경우 overwrite ? -> yes

permissions:
  # 복사한 파일에 대한 권한 설정
  - object: /
    # 권한이 지정되는 디렉토리 or 파일
    pattern: "**"
    # 매칭 되는 패턴에만 권한부여
    owner: ubuntu
    # object 소유자
    group: ubuntu
    # object 그룹

hooks:
  # 배포 이후 수행할 스크립트
  AfterInstall:
    # 기존 실행중이던 Application 종료
    - location: scripts/stop.sh
      # 실행할 스크립트 위치
      timeout: 60
      # 스크립트 실행에 허용되는 최대시간, 허용된 시간 초과시 배포실패
      runas: ubuntu
      # 스크립트를 실행하는 사용자
  ApplicationStart:
    # 새로운 Application 실행
    - location: scripts/start.sh
      timeout: 60
      runas: ubuntu